version: '3'

services:
  mysql:
    image: mysql:8
    container_name: code-review-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: codecheck
      MYSQL_USER: codecheck
      MYSQL_PASSWORD: codecheck_password
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      LANG: C.UTF-8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ../code-review-api/app/db/MySQL.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - "13306:3306"
    networks:
      - code-review-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "codecheck", "-pcodecheck_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: ../code-review-api
      dockerfile: ../docker/backend/Dockerfile
    container_name: code-review-api
    env_file:
      - ../code-review-api/.env.production
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - code-review-network
    restart: always

  web:
    build:
      context: ../code-review-web
      dockerfile: ../docker/frontend/Dockerfile
    container_name: code-review-web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - code-review-network
    restart: always

networks:
  code-review-network:
    driver: bridge

volumes:
  mysql_data: 